//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.12 at 11:58:48 AM CAT 
//


package NedbankSample;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TestSexType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TestSexType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Black"/>
 *     &lt;enumeration value="Hazel"/>
 *     &lt;enumeration value="Gray"/>
 *     &lt;enumeration value="Brown"/>
 *     &lt;enumeration value="Violet"/>
 *     &lt;enumeration value="Green"/>
 *     &lt;enumeration value="Blue"/>
 *     &lt;enumeration value="Maroon"/>
 *     &lt;enumeration value="Pink"/>
 *     &lt;enumeration value="Dichromatic"/>
 *     &lt;enumeration value="Unknown"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TestSexType", namespace = "base")
@XmlEnum
public enum TestSexType {

    @XmlEnumValue("Black")
    BLACK("Black"),
    @XmlEnumValue("Hazel")
    HAZEL("Hazel"),
    @XmlEnumValue("Gray")
    GRAY("Gray"),
    @XmlEnumValue("Brown")
    BROWN("Brown"),
    @XmlEnumValue("Violet")
    VIOLET("Violet"),
    @XmlEnumValue("Green")
    GREEN("Green"),
    @XmlEnumValue("Blue")
    BLUE("Blue"),
    @XmlEnumValue("Maroon")
    MAROON("Maroon"),
    @XmlEnumValue("Pink")
    PINK("Pink"),
    @XmlEnumValue("Dichromatic")
    DICHROMATIC("Dichromatic"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    TestSexType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TestSexType fromValue(String v) {
        for (TestSexType c: TestSexType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
